<!-- widget grid -->
	<section id="widget-grid" class="">

		<div class="row">

			<!-- NEW WIDGET START -->
			<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				
				<!-- Widget ID (each widget will need unique ID)-->
				<div class="jarviswidget" id="wid-id-0">
					<!-- widget options:
						usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">
						
						data-widget-colorbutton="false"	
						data-widget-editbutton="false"
						data-widget-togglebutton="false"
						data-widget-deletebutton="false"
						data-widget-fullscreenbutton="false"
						data-widget-custombutton="false"
						data-widget-collapsed="true" 
						data-widget-sortable="false"
						
					-->
					<header>
						<span class="widget-icon"> <i class="fa fa-table"></i> </span>
						<h2>&nbsp;Tables</h2>				
						
					</header>
	
					<!-- widget div-->
					<div>
						
						<!-- widget edit box -->
						<div class="jarviswidget-editbox">
							<!-- This area used as dropdown edit box -->
							<input class="form-control" type="text">	
						</div>
						<!-- end widget edit box -->
						
						<!-- widget content -->
						<div class="widget-body">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>
											#
										</th>
										<th>
											Name
										</th>
										<th>
											Pack
										</th>
										<th>
											Quota
										</th>
										<th>
											Quota valid until
										</th>
										<th>
											Demo valid until
										</th>
										<th>
											Tests Pending/All
										</th>
										<th>
											Status framework
										</th>
										<th>
											Account manager
										</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr>
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr class="active">
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr>
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr>
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr>
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr>
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr>
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr class="warning">
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr>
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr class="success">
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr>
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr>
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr class="danger">
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
									<tr>
										<td>
											1
										</td>
										<td>
											julien.bonin@liwio.com
										</td>
										<td>
											Premium
										</td>
										<td>
											0
										</td>
										<td>
											2015-06-15
										</td>
										<td>
											2015-06-01
										</td>
										<td>
											0/0
										</td>
										<td>
											Check
										</td>
										<td>
											remi@liwio.com
										</td>
									</tr>
								</tbody>
							</table>
						</div>
						<!-- end widget content -->
						
					</div>
					<!-- end widget div -->
					
				</div>
				<!-- end widget -->
	
			</article>
			<!-- WIDGET END -->
			
		</div>
	
		<!-- end row -->
	
		<!-- row -->
	</section>